### ISSUE TITLE
elixir error

### ISSUE THREAD

**Issue by FinalDes** [hisman/laravel-elixir-imagemin-wrapper#1]
/Users/alex/Code/aladdin2/node_modules/laravel-elixir-imagemin-wrapper/index.js:54
    return new Elixir.GulpPaths()
           ^
TypeError: undefined is not a function
    at prepGulpPaths (.../node_modules/laravel-elixir-imagemin-wrapper/index.js:54:12)
    at Object.imagemin (.../node_modules/laravel-elixir-imagemin-wrapper/index.js:25:17)
    at .../gulpfile.js:16:9
    at Elixir (/.../node_modules/laravel-elixir/index.js:3:5)
    at Object.<anonymous> (.../gulpfile.js:15:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by hisman** [comment]
Hi, 

it seems fine to me, can you tell me what version of your elixir & laravel?

**Comment by FinalDes** [comment]
version 3.2.5
I use laravel 5.1

**Comment by hisman** [comment]
Sorry, I can't reproduce the error. Maybe deleting your **node_modules** folder and doing `node install` again could help.
